version: '3.8'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_banks
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo_banks
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
    ports:
      - '27017:27017'

  nginx:
    image: nginx
    container_name: nginx_banks
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express

  redis:
    image: redis
    container_name: redis_banks
    restart: unless-stopped
    ports:
      - '6380:6379'

volumes:
  mongo_data:
    external: true